# Biblbiotecas

In [25]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Carga de datos

In [26]:
df = pd.read_csv('restaurantData.csv')

# Ajuste de los valores de categorías csv

In [27]:
df.head()

,class,alternate,bar,fri/sat,hungry,patrons,price,raining,reservation,type,waitestimate
0,wontwait,no,no,no,yes,none,DDD,no,yes,thai,0
1,willwait,yes,yes,no,yes,some,DDD,no,no,thai,0
2,willwait,yes,no,yes,yes,some,DD,no,no,thai,10
3,willwait,yes,no,no,yes,some,D,yes,no,italian,0
4,wontwait,no,no,no,no,none,DDD,no,no,french,60

In [28]:
# Cambio de categorías con label encoding
columnas_object = df.select_dtypes(include=['object']).columns
df_encoded = df.copy()
df_encoded[columnas_object] = df[columnas_object].apply(LabelEncoder().fit_transform)

In [29]:
df_encoded.head()

,class,alternate,bar,fri/sat,hungry,patrons,price,raining,reservation,type,waitestimate
0,1,0,0,0,1,1,2,0,1,3,0
1,0,1,1,0,1,2,2,0,0,3,0
2,0,1,0,1,1,2,1,0,0,3,10
3,0,1,0,0,1,2,0,1,0,2,0
4,1,0,0,0,0,1,2,0,0,1,60

In [30]:
for columna in df.columns:
    orig_vals = df[columna].unique()
    encoded_vals = df_encoded[columna].unique()
    
    print(f"Columna: '{columna}'")
    print(f"\t-Original:   {orig_vals}")
    print(f"\t-Codificado: {encoded_vals}")
    print()

Columna: 'class'
	-Original:   [' wontwait' ' willwait']
	-Codificado: [1 0]

Columna: 'alternate'
	-Original:   [' no' ' yes']
	-Codificado: [0 1]

Columna: 'bar'
	-Original:   [' no' ' yes']
	-Codificado: [0 1]

Columna: 'fri/sat'
	-Original:   [' no' ' yes']
	-Codificado: [0 1]

Columna: 'hungry'
	-Original:   [' yes' ' no']
	-Codificado: [1 0]

Columna: 'patrons'
	-Original:   [' none' ' some' ' full']
	-Codificado: [1 2 0]

Columna: 'price'
	-Original:   [' DDD' ' DD' ' D']
	-Codificado: [2 1 0]

Columna: 'raining'
	-Original:   [' no' ' yes']
	-Codificado: [0 1]

Columna: 'reservation'
	-Original:   [' yes' ' no']
	-Codificado: [1 0]

Columna: 'type'
	-Original:   [' thai' ' italian' ' french' ' burger']
	-Codificado: [3 2 1 0]

Columna: ' waitestimate'
	-Original:   [ 0 10 60 30]
	-Codificado: [ 0 10 60 30]